spring:
  application:
    name: spring-cloud-user
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      percentage: 1.0

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/,http://peer3:8762/eureka/