spring:
  application:
    name: spring-cloud-eureka
  profiles: peer3
server:
  port: 8762
eureka:
  instance:
    hostname: peer3
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer1:8760/eureka/,http://peer2:8761/eureka/