spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1
  zipkin:
    base-url: http://localhost:9000
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 8760
eureka:
  instance:
    hostname: peer1
  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/,http://peer3:8762/eureka/
zuul:
  routes:
    consumer:
      path: /consumer/**
      serviceId: spring-cloud-consumer
    user:
      path: /user/**
      serviceId: spring-cloud-user